# <center>Numpy矩阵</center>

# 1. 创建矩阵
    * 使用mat 函数创建矩阵
    * 使用matrix 函数创建矩阵
    * 使用bmat创建矩阵

1. 使用mat 函数创建矩阵

In [1]:
import numpy as np

matr1 = np.mat('1,2,3;4,5,6;7,8,9')
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

2. 使用matrix 函数创建矩阵

In [2]:
matr2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matr2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

3. 使用bmat函数创建矩阵  
bmat 为分块矩阵函数，可以根据小的矩阵创建大的矩阵

In [3]:
arr1 = arr4 =np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
arr2 = arr3 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
matr3 = np.bmat("arr1 arr2; arr3 arr4")
matr3

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

# 2. 矩阵运算
* \+：	矩阵对应元素相加
* \-：	矩阵对应元素相减
*  \*：	矩阵对应元素相乘

In [1]:
import numpy as np

In [6]:
matr1 = np.mat('1,2,3;4,5,6;7,8,9')
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
matr2 = np.mat('1,2,3;4,5,6;7,8,9')
matr2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
# 矩阵相加
matr3 = matr1 + matr2
matr3

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [9]:
## 矩阵相减
matr4 = matr1 - matr2
matr4

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
## 矩阵相乘（点乘）
matr5 = matr1 * matr2
matr5

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [11]:
# 等用于 dot 函数
matr6 = matr1.dot(matr2)
matr6

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [12]:
# 与数组的乘法区别开
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)
c = a * b
c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# 3. 矩阵属性
* T ： 返回自身的转置
* H ： 返回自身的共轭转置
* I ： 返回自身的逆矩阵
* A ： 返回自身数据的二维数组的一个视图

In [2]:
matr1 = np.mat('1,2,3;4,5,6;7,8,9')
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
#返回自身的转置
matr1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [4]:
# 返回自身的共轭转置
matr1.H

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [16]:
# 返回自身的逆矩阵
matr1.I

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [17]:
# 返回自身数据的二维数组的一个视图
matr1.A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])