# <center>掌握ufunc函数</center>

# 1. 常用的ufunc函数

能够对数组中所有元素进行操作的函数  
* 四则运算：加（+）、减（-）、乘（\*）、除（/）、幂（\*\* ）。数组间的四则运算表示对每个数组中的元素分别进行四则运算，所以形状必须相同。
* 比较运算：>、<、==、>=、<=、!=。比较运算返回的结果是一个布尔数组，每个元素为每个数组对应元素的比较结果。
* 逻辑运算：np.any函数表示逻辑“or”，np.all函数表示逻辑“and”。运算结果返回布尔值。

### 四则运算

In [1]:
import numpy as np
# 声明3个numpy 数组
arr1 = np.array([11, 12, 13])
arr2 = np.array([21, 22, 23])
arr3 = np.array([31, 32, 33])

# numpy 的四则运算， 使用 + - * / **，  可以连续运算， 3个或以上都可以

print('arr1和arr2的相加{}'.format(arr1+arr2))
print('arr1和arr2，arr3的连续相加{}'.format(arr1+arr2+arr3))

print('arr1减arr2{}'.format(arr1-arr2))
print('arr1,arr2,arr3的连续相减{}'.format(arr1-arr2-arr3))

print('arr1和arr2的相乘{}'.format(arr1*arr2))

print('arr1和arr2的相除{}'.format(arr1/arr2))
print('arr1d的幂运算{}'.format(arr1**2**2))

arr1和arr2的相加[32 34 36]
arr1和arr2，arr3的连续相加[63 66 69]
arr1减arr2[-10 -10 -10]
arr1,arr2,arr3的连续相减[-41 -42 -43]
arr1和arr2的相乘[231 264 299]
arr1和arr2的相除[0.52380952 0.54545455 0.56521739]
arr1d的幂运算[14641 20736 28561]


In [2]:
# numpy的四则运算，  使用方法 .add  .subtract    .multiply   .divide，  .power不能连续运算， 只能2个

print('arr1和arr2相加{}'.format(np.add(arr1, arr2)))
print('arr1和arr2相减{}'.format(np.subtract(arr1, arr2)))
print('arr1和arr2相乘{}'.format(np.multiply(arr1, arr2)))
print('arr1和arr2相除{}'.format(np.divide(arr1, arr2)))
print('arr1d的幂运算{}'.format(np.power(arr1,2)))

arr1和arr2相加[32 34 36]
arr1和arr2相减[-10 -10 -10]
arr1和arr2相乘[231 264 299]
arr1和arr2相除[0.52380952 0.54545455 0.56521739]
arr1d的幂运算[121 144 169]


### 比较运算
对两个形状相同的numpy数组进行大于比较得到的结果是一个与数组的形状相同的numpy数组，数组中元素的数据类型为布尔类型

In [3]:
arr =np.array([1,5,7,2,3])
arr2 = np.array([2,3,7,5,9])
res =arr>arr2
print(res)
print("比较结果的数据类型为：",type(res))
print("比较结果中的元素的数据类型为：",type(res[0]))

[False  True False False False]
比较结果的数据类型为： <class 'numpy.ndarray'>
比较结果中的元素的数据类型为： <class 'numpy.bool_'>


### 逻辑运算
python中有and，or，not三个逻辑运算符，numpy中的逻辑运算使用别的名字来进行逻辑运算。

In [4]:
#python中的逻辑运算
a = np.array([True, False,True])
b = np.array([False, False,True])
#与运算
print("a and b=",np.logical_and(a,b))
#或运算
print("a or b=", np.logical_or(a, b))
#非运算
print("a not b=", np.logical_not(a, b))
#异或运算
print("a xor b=", np.logical_xor(a, b))

a and b= [False False  True]
a or b= [ True False  True]
a not b= [False  True False]
a xor b= [ True  True  True]


In [5]:
arr =np.array([1,5,7,2,3])
arr2 = np.array([2,3,7,5,9])
print("arr>arr2：",arr>arr2)
print("any()?",np.any(arr>arr2))
print("all()?",np.all(arr>arr2))

arr>arr2： [False  True False False False]
any()? True
all()? False


# 2. ufunc函数的广播机制

***广播：***  
简单理解为用于不同大小数组的二元通用函数（加、减、乘等）的一组规则

***广播的规则：***
* 让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐。
* 输出数组的shape是输入数组shape的各个轴上的最大值。
* 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错。
* 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值。

### 实例1：二维数组加一维数组

In [6]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
b = np.array([[0, 1, 2],[0, 1, 2]])
b

array([[0, 1, 2],
       [0, 1, 2]])

In [8]:
a.shape, b.shape

((2, 3), (3,))

In [12]:
# 形状不匹配但是可以相加
a + b

array([[1., 2., 3.],
       [1., 2., 3.]])

***分析：a.shape=(2, 3), b.shape=(3,)***
1. 根据规则1，b.shape会变成(1, 3)
2. 根据规则4，使用此轴上的第一组值，相当于在行上复制，b.shape再变成(2, 3)，
3. 完成匹配

### 实例2：两个数组均需要广播

In [13]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [14]:
b = np.arange(3)
b

array([0, 1, 2])

In [15]:
a.shape, b.shape

((3, 1), (3,))

In [16]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [19]:
a = np.array([[0,0,0],[1,1,1],[2,2,2]])
a

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [20]:
b = np.array([[0, 1, 2],[0, 1, 2],[0, 1, 2]])
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [21]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

***分析：a.shape为(3,1)，b.shape为(3,)***：
1. 根据规则1，b.shape会变成(1, 3)
2. 根据规则4，b.shape再变成(3, 3)，相当于在行上复制
3. 根据规则4，a.shape再变成(3, 3)，相当于在列上复制
3. 完成匹配

In [ ]:
print('a:\n',np.array([[0,0,0],[1,1,1],[2,2,2]]))
print('b:\n',np.array([[0, 1, 2],[0, 1, 2],[0, 1, 2]]))
np.array([[0,0,0],[1,1,1],[2,2,2]]) + np.array([[0, 1, 2],[0, 1, 2],[0, 1, 2]])

### 实例3：不匹配的例子

In [22]:
a = np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
b = np.arange(3)
b

array([0, 1, 2])

In [24]:
a.shape, b.shape


((3, 2), (3,))

In [25]:
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

***分析：a.shape为(3,2)，b.shape为(3,)***：
1. 根据规则1，b.shape会变成(1, 3)
2. 根据规则4，b.shape再变成(3, 3)，相当于在行上复制
3. 根据规则3，a.shape为(3,2)，b.shape为(3,3)，形状不匹配，并且没有维度是1，匹配失败报错