# <center>2. Numpy进行简单统计分析</center>

1. 排序
2. 去重和重复数据
3. 常用的统计函数

# 1. 排序
* 直接排序
    * sort 按值大小排序
* 间接排序
    * argsort 排序，返回的时从小到大的元素的索引
    * lexsort 对于多个序列进行排序，返回索引

### 1. sort  按值大小排序  
ndarray.sort(axis=-1, kind='quicksort', order=None)
* axis:	排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认值为-1，表示沿最后的轴排序
* kind:	排序的算法，提供了快排'quicksort'、混排'mergesort'、堆排'heapsort'， 默认为‘quicksort'
* order:	排序的字段名，可指定字段排序，默认为None

In [1]:
import numpy as np
x=np.array([[0,12,48],[4,18,14],[7,1,99]])
 
print(np.sort(x))
x

[[ 0 12 48]
 [ 4 14 18]
 [ 1  7 99]]


array([[ 0, 12, 48],
       [ 4, 18, 14],
       [ 7,  1, 99]])

In [2]:
import numpy as np
x= np.array([[0,12,48],[4,18,14],[7,1,99]])
 
x.sort() # 原始数据会被修改
x

array([[ 0, 12, 48],
       [ 4, 14, 18],
       [ 1,  7, 99]])

In [3]:
# 按列排序
np.sort(x,axis=0)

array([[ 0,  7, 18],
       [ 1, 12, 48],
       [ 4, 14, 99]])

In [4]:
# order 主要用于自定义数据结构
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("Mike",21),("Nancy",25),("Bob",  17),  ("Jane",27)], dtype = dt)
np.sort(a, order =  'name')

array([(b'Bob', 17), (b'Jane', 27), (b'Mike', 21), (b'Nancy', 25)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [5]:
np.sort(a, order =  'age')

array([(b'Bob', 17), (b'Mike', 21), (b'Nancy', 25), (b'Jane', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

### 2. argsort 多个键排序
np.argsort(axis, kind=None, order=None) 对数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。

In [6]:
# 一维数组
x=np.array([-1,4,3,-1,6,9])
# 将x中的元素从小到大排列，返回其对应的index(索引)
np.argsort(x)

array([0, 3, 2, 1, 4, 5], dtype=int64)

In [7]:
# 二维数组
x=np.array([[0,12,48],[4,18,14],[7,1,99]])
# 按行排序
np.argsort(x, axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [8]:
# 按列排序
np.argsort(x, axis=0)

array([[0, 2, 1],
       [1, 0, 0],
       [2, 1, 2]], dtype=int64)

### 3. lexsort
lexsort(keys, axis=-1) 函数可对于多个序列进行排序，不修改原数组

In [9]:
a=np.array([1,5,1,4,3,4,4])
b=np.array([9,4,0,4,0,2,1])
# 将长度相同的a，b组合，向根据a值的大小进行排序，再考虑b值
ind=np.lexsort((b,a))
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [10]:
list(zip(a[ind],b[ind]))

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

## 2. 去重与重复数据


* unique 
* tie
* repeat

### 1. unique
 numpy.unique(arr) 函数可以找出数组中的唯一值并返回已排序的结果

In [11]:
arr = np.array([1,1,1,2,2,3,3,])
res = np.unique(arr)
res

array([1, 2, 3])

In [34]:
arr = np.array([1,1,1,2,2,3,3,])

res_unique,res_counts = np.unique(arr,return_counts = True)
res,res_counts

((array([1, 2, 3]), array([3, 2, 2], dtype=int64)),
 array([3, 2, 2], dtype=int64))

### 2. tile
np.tile(A，reps)
* A:指定重复的数组
* reps:指定重复的次数数

In [13]:
arr1 = np.arange(5)
print(arr1)
arr2 = np.tile(arr1,3)
arr2

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [14]:
arr1 = np.arange(5).reshape((5,1))
print(arr1)
arr2 = np.tile(arr1,3)
arr2

[[0]
 [1]
 [2]
 [3]
 [4]]


array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

###  3.repeat
numpy.repeat(a, repeats, axis=None) 重复
* a：须要重复的数组元素
* repeats：重复次数 
* axis：指定沿着哪一个轴进行重复，axis = 0 表示按行进行元素重复；axis =1 表示按列进行元素重复。

In [15]:
arr2 = np.random.randint(0,10,size=(3,3))
print('arr2:\n',arr2)

arr2:
 [[6 5 9]
 [8 2 6]
 [3 1 1]]


In [16]:
arr2_2 = np.repeat(arr2,2,axis=0)
print('按行进行重复',arr2_2)

按行进行重复 [[6 5 9]
 [6 5 9]
 [8 2 6]
 [8 2 6]
 [3 1 1]
 [3 1 1]]


In [17]:
arr2_2 = np.repeat(arr2,2,axis=1)
print('按行进行重复',arr2_2)

按行进行重复 [[6 6 5 5 9 9]
 [8 8 2 2 6 6]
 [3 3 1 1 1 1]]


### repeat和tile两个函数都可以对数组进行“重复”区别在于：
* tile函数是将数组进行重复，repeat函数是对数组中的每一个元素进行重复

# 2. 常用的统计函数

1. 求和函数 numpy.sum(a, axis=None)------a.sum(axis=None)

2. 求均值 numpy.mean(a, axis=None)-----a.mean(axis=None)

3. 加权平均值numpy.average(a,axis=None,weights=None)

4. 标准差numpy.std(a,axis=None)-------a.std(axis=None)

5. 方差numpy.var(a,axis=None)--------a.var(axis=None)

6. 最小值/最大值 numpy.amin(a,axis=None)/numpy.max(a,axis=None)-------a.min(axis=None)/a.max(axis=None)

7. 最小值索引一维下标numpy.argmin(a,axis=None)---------a.argmin(axis=None)

8. 最大值索引numpy.argmax(a,axis=None)---------a.argmax(axis=None)

9. 中位数numpy.median(a,axis=None)

10. 百分位数numpy.percentile(a, q, axis=None)

### 案例：分析学生成绩


In [18]:
fileName='../data/stu.txt'
dataArr = data_array=np.loadtxt(fileName,  skiprows=1,  dtype=float)       
dataArr                     

array([[ 76.,  59., 100.,  78.,  71.],
       [ 75.,  94.,  83.,  63.,  65.],
       [ 83.,  76.,  92.,  73.,  82.],
       ...,
       [ 67.,  56.,  83.,  78.,  57.],
       [ 81.,  94.,  99.,  64.,  88.],
       [ 78.,  79.,  88.,  60.,  71.]])

In [19]:
dataArr.shape

(1380, 5)

In [20]:
tempData = dataArr[0:10]
tempData

array([[ 76.,  59., 100.,  78.,  71.],
       [ 75.,  94.,  83.,  63.,  65.],
       [ 83.,  76.,  92.,  73.,  82.],
       [ 64.,  81., 100.,  70.,  78.],
       [ 63.,  76.,  98.,  64.,  53.],
       [ 71.,  81.,  87.,  65.,  48.],
       [ 77.,  77.,  79.,  79.,  84.],
       [ 67.,  60.,  87.,  60.,  45.],
       [ 74.,  91.,  94.,  60.,  95.],
       [ 69.,  98.,  92.,  67.,  83.]])

In [21]:
# 计算总分
sumArr = np.sum(tempData,axis=1)
sumArr

array([384., 380., 406., 393., 354., 352., 396., 319., 414., 409.])

In [22]:
sumArr = np.sum(tempData,axis=0)
sumArr

array([719., 793., 912., 679., 704.])

In [23]:
# 计算平均分
meanRowArr = np.mean(tempData,axis = 1 )
meanRowArr

array([76.8, 76. , 81.2, 78.6, 70.8, 70.4, 79.2, 63.8, 82.8, 81.8])

In [24]:
#计算科目平均分
meanColArr = np.mean(tempData,axis = 0 )
meanColArr

array([71.9, 79.3, 91.2, 67.9, 70.4])

In [25]:
# 计算方差
stdRowArr = np.std(tempData,axis=1)
stdRowArr

array([13.34765897, 11.52388823,  6.55438784, 12.25724276, 15.43243338,
       13.55876101,  2.56124969, 13.64404632, 13.70255451, 12.25397895])

In [26]:
# 查看科目中位数
np.median(dataArr,axis = 0)

array([76., 77., 89., 70., 70.])

In [27]:
# 查看科目最高分
np.amax(dataArr,axis=0)

array([ 89., 100., 100.,  80., 100.])

In [28]:
# 查看科目最低分
np.amin(dataArr,axis=0)

array([63., 55., 78., 60., 40.])

In [29]:
# 统计数学大于80分的个数
np.sum(dataArr[:,0]>80)

433

### 上述的计算称之为聚合计算  
聚合计算概念：对一组值执行计算并返回单一的值

### 非聚合计算 ：产生一个由中间结果组成的数组
* cumsum： 计算所有元素的累计和
* cumprod：计算所有元素的累计积

In [30]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# 计算所有元素的累计和
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [32]:
# 计算所有元素的累计积
np.cumprod(arr)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)