# Numpy对数组按索引查询

三种索引方法：
* 基础索引
* 整数数组索引
* 布尔索引

In [1]:
import numpy as np

##  1. 基础索引

### 1.1  一维数组

和Python的List一样

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#  使用下标索引来访问列表中的值
# 正索引：从左向右 0，1，2，3......
# 负索引：从右向左， -1，-2，-3
print(x[2], x[9], x[-1],x[-10])

2 9 9 0


In [4]:
# 使用切片来访问特定范围内的元素
# 切片语法：[start:stop:step]，其中start代表起始索引；stop代表终止索引；step代表步长
x[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [5]:
# 切片时允许正负索引同时使用
x[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [6]:
#也可以只使用负索引
print(x[-3:])
print(x[:-3])

[7 8 9]
[0 1 2 3 4 5 6]


In [7]:
# 切片第三个参数步长
x[0:9:2]

array([0, 2, 4, 6, 8])

###  1.2 多维数组

多维数组每一个维度有一个索引，各个维度之间用逗号隔开

In [8]:
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
# 分别用行坐标、列坐标，实现行列筛选
print(X[0, 0],X[2,3],X[-1,3])

0 13 18


In [10]:
# 行筛选
print('第三行:',X[2])
print('倒数第三行:',X[-3])

第三行: [10 11 12 13 14]
倒数第三行: [5 6 7 8 9]


In [11]:
# 筛选列
X[:, 2]

array([ 2,  7, 12, 17])

In [12]:
# 筛选多行
X[:-2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
#筛选多列
X[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [14]:
# 筛选多行，然后筛选多列
X[:2, 2:4]

array([[2, 3],
       [7, 8]])

####  注意：切片的修改会修改原来的数组

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[2:4] = 666
x

array([  0,   1, 666, 666,   4,   5,   6,   7,   8,   9])

In [17]:
# 修改第0行，第1，2列的值
X[:1, :2] = 666
X

array([[666, 666,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

## 2 整数数组索引


### 2.1 一维数组

In [18]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
x[[3,4,7]]

array([4, 5, 8])

In [20]:
indexs = np.array([[0, 2], [1, 3]])
x[indexs]

array([[1, 3],
       [2, 4]])

#### 实例：获取数组中最大的前N个数字

In [21]:
# 随机生成1到100之间的，10个数字
arr = np.random.randint(1,100,10)
arr

array([67, 60, 60, 38, 31, 41, 17, 40, 85, 19])

In [22]:
# arr.argsort()会返回排序后的索引index
# 取最大值对应的3个下标
arr.argsort()[-3:]

array([2, 0, 8], dtype=int64)

In [23]:
arr[arr.argsort()[-3:]]

array([60, 67, 85])

### 2.2 二维数组 

In [24]:
X  = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
# 筛选多行，列可省略
X[[0, 2]]  # 等同于X[[0, 2], :]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [26]:
# 筛选多列，行不能省略
X[:, [0,2,3]]

array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])

In [27]:
# 同时指定行列-列表
# 返回的是[(0,1), (2,3), (3,4)]位置的数字
X[[0, 2, 3], [1, 3, 4]]

array([ 1, 13, 19])

## 3. 布尔索引

### 3.1 一维数组

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [30]:
x[x>5]

array([6, 7, 8, 9])

### 3.2  二维数组

In [31]:
X  = np.arange(20).reshape(5,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
X % 4 == 0

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [33]:
# X % 4 == 0的boolean数组，既有行，又有列
# 因此返回的是一维结果
X[X % 4 == 0]

array([ 0,  4,  8, 12, 16])

In [34]:
# 举例：怎样把第3列大于10的行筛选出来
X[:, 2]

array([ 2,  6, 10, 14, 18])

In [35]:
X[:, 2]>10

array([False, False, False,  True,  True])

In [36]:
# 这里是按照行进行的筛选
X[X[:, 2]>10,2]

array([14, 18])

In [37]:
X[X[:, 2]>10,2] = 666
X

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13, 666,  15],
       [ 16,  17, 666,  19]])

### 条件的组合

In [38]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
condition = (x%2==0) | (x>7)
condition

array([ True, False,  True, False,  True, False,  True, False,  True,
        True])

In [48]:
x[condition]

array([0, 2, 4, 6, 8, 9])