# <center>变换数组形态</center>

* 改形
    * reshape:在不改变数据的情况下为数组赋予新的形状
    * resize: 改变自身数组的形态
* 展平
    * ravel：将多维数组变一维数组,横向展平
    * flatten：将多维数组变一维数组，可以横向展平，也可以纵向展平
* 组合
    * hstack：数组横向组合
    * vstack：数组纵向组合
    * concatenate: 实现数组的横向组合和纵向组合
* 分割
    * hsplit: 对数组按列进行分割
    * vsplit: 对数组按行进行分割
    * split： 数据分割

## 1. reshape
reshape(shape, order='C')：在不改变数据的情况下为数组赋予新的形状
* order C:横向；F:纵向
* reshape函数生成的新数组和原始数组公用一个内存，也就是说，不管是改变新数组还是原始数组的元素，另一个数组也会随之改变

In [1]:
import numpy as np
x = np.arange(1,17)
X = x.reshape(4,4,order='C') # 等同于 np.reshape(x,shape,order)
x[2]= 999
print('x:\n',x)
print('X:\n',X)

x:
 [  1   2 999   4   5   6   7   8   9  10  11  12  13  14  15  16]
X:
 [[  1   2 999   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]


In [2]:
# shape参数的其中一维可以是-1，表示该维度上的长度会自动根据数组的长度及其余维度的长度自动推断出来
x1 = X.reshape(-1) # 等同于 X.reshape(16)
x1

array([  1,   2, 999,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16])

In [3]:
# 不知道行，知道列数，使用行位置填充-1进行自动计算
X.reshape(-1,8)

array([[  1,   2, 999,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16]])

In [4]:
# 知道行，不知道列
X.reshape(2,-1)

array([[  1,   2, 999,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16]])

## 2. resize
x.resize(shape) 改变x自身的形态

In [5]:
x = np.arange(4)
print('x改形前的shape：',x.shape)
x.resize(2,4)
print('x改形后的shape：',x.shape)  
print("x:\n",x)

x改形前的shape： (4,)
x改形后的shape： (2, 4)
x:
 [[0 1 2 3]
 [0 0 0 0]]


## 3. revel 
x.ravel() 将多维数组变一维数组

In [6]:
X = np.arange(1,17).reshape(4,4)
b = X.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [7]:
b[3]= 666
print('b:\n', b)
print('X:\n', X)

b:
 [  1   2   3 666   5   6   7   8   9  10  11  12  13  14  15  16]
X:
 [[  1   2   3 666]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]


## 4.flatten
flatten(order='C')其功能与ravel()相同，但是flatten()返回的是真实的数组
* order C:横向；F:纵向

In [8]:
X = np.arange(1,17).reshape(4,4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [9]:
c = X.flatten('C')
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
d = X.flatten('F')
d

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [11]:
c[2]= 666
print('c:\n', c)
print('X:\n', X)

c:
 [  1   2 666   4   5   6   7   8   9  10  11  12  13  14  15  16]
X:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 5. hstack 
numpy.hstack(tup)  数组横向组合
* tup是arrays组成的元组
* 该函数相当于沿第二个轴连接（axis=1），除了一维数组的堆叠可以是不同长度外，其它数组堆叠时，除了第二个轴的长度可以不同外，其它轴的长度必须相同。

In [12]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a1 =np.arange(1,13).reshape(2,1,6)
print('数组a1的shape：',a1.shape)
print('数组a1：\n',a1)

数组a1的shape： (2, 1, 6)
数组a1：
 [[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]


In [14]:
b1 = np.arange(1,25).reshape(2,2,6)
print('数组b1的shape：',b1.shape)
print('数组b1：\n',b1)

数组b1的shape： (2, 2, 6)
数组b1：
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [15]:
c1 = np.hstack((a1,b1))
print('组合后数组的shape：',c1.shape)
print('数组c1：\n',c1)

组合后数组的shape： (2, 3, 6)
数组c1：
 [[[ 1  2  3  4  5  6]
  [ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


## 6. vstack
numpy.vstack(tup) 数组纵向组合
* tup是arrays组成的元组
* 该函数相当于沿第一个轴连接（axis=0），与其它数组堆叠时，除数组第一个轴的长度可以不同，其它轴长度必须一样。

In [16]:
a = np.arange(1,3)
b = np.arange(5,7)
c = np.vstack((a,b))
c

array([[1, 2],
       [5, 6]])

In [17]:
a2 =np.arange(1,13).reshape(1,2,6)
print('数组a2的shape：',a2.shape)
print('数组a2：\n',a2)

数组a2的shape： (1, 2, 6)
数组a2：
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]


In [18]:
b2 = np.arange(1,25).reshape(2,2,6)
print('数组b2的shape：',b2.shape)
print('数组b2：\n',b2)

数组b2的shape： (2, 2, 6)
数组b2：
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [19]:
c2 = np.vstack((a2,b2))
print('组合后数组的shape：',c2.shape)
print('数组c2：\n',c2)

组合后数组的shape： (3, 2, 6)
数组c2：
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


## 7. concatenate
numpy.concatenate((tup),axis) 实现数组的横向组合和纵向组合
*  axis = 1 时，等同于 np.hstack
*  axis = 0 时，等用于 np.vstack

In [20]:
a2 = np.arange(1,13).reshape(2,1,6)
b2 = np.arange(1,25).reshape(2,2,6)
c1 = np.concatenate((a1,b1),axis=1)
print(c1)

[[[ 1  2  3  4  5  6]
  [ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [21]:
a2 = np.arange(1,13).reshape(1,2,6)
b2 = np.arange(1,25).reshape(2,2,6)
c2 = np.concatenate((a2,b2),axis=0)
print(c2)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


##  8. hsplit
numpy.hsplit(ary, indices_or_sections) 将数组横向分割成大小相同的子数组

In [22]:
s1 = np.arange(1,17).reshape(4,4)
arr = np.hsplit(s1,2)
arr

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [23]:
arr[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

## 9. vsplit
numpy.vsplit(ary, indices_or_sections) 将数组纵向分割成大小相同的子数组

In [24]:
arr2 = np.vsplit(s1,2)
arr2

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [25]:
arr2[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 10 split
np.split(ary, indices_or_sections, axis=0)  分割数组
* axis = 1 时，等同于 np.hsplit
* sxis = 0 时，等同于 np.vsplit

In [26]:
np.split(s1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [27]:
np.split(s1,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]